- link: "project/nova-victoria-building-5"
  imagePath: asset/image/project/nova-victoria-building-5/main-nova-victoria-building.jpg
  imageList:
    - asset/image/project/nova-victoria-building-5/nova-victoria-building-1.png
    - asset/image/project/nova-victoria-building-5/nova-victoria-building-2.png
    - asset/image/project/nova-victoria-building-5/nova-victoria-building-3.png
    - asset/image/project/nova-victoria-building-5/nova-victoria-building-4.png
    - asset/image/project/nova-victoria-building-5/nova-victoria-building-5.jpg
  title: Nova Victoria Building 5
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/135-bishops-gate"
  imagePath: asset/image/project/135-bishops-gate/main-bishop.jpg
  imageList:
    - asset/image/project/135-bishops-gate/135-bishop-1.jpg
    - asset/image/project/135-bishops-gate/135-bishop-2.jpg
    - asset/image/project/135-bishops-gate/135-bishop-3.jpg
    - asset/image/project/135-bishops-gate/135-bishop-4.jpg
    - asset/image/project/135-bishops-gate/135-bishop-5.jpg
  title: 135 Bishops Gate
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/undershaft"
  imagePath: asset/image/project/undershaft/main-1-Undershaft-4.jpg
  imageList:
    - asset/image/project/undershaft/undershaft-1.jpg
    - asset/image/project/undershaft/undershaft-2.jpg
    - asset/image/project/undershaft/undershaft-3.jpg
    - asset/image/project/undershaft/undershaft-4.jpg
  title: Undershaft
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/11-15-grosvenor-cresent"
  imagePath: asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-3.jpg
  title: 11-15 Grosvenor Cresent
  imageList:
    - asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-2.jpg
    - asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-3.jpg
    - asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-4.jpg
    - asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-5.jpg
    - asset/image/project/11-15-grosvenor-cresent/Grosvenor-Crescent-6.jpg
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!

- link: "project/30-cannon-street"
  imagePath: asset/image/project/30-cannon-street/main-cannon-street.jpg
  title: 30 Cannon Street
  imageList:
    - asset/image/project/30-cannon-street/cannon-street-1.jpg
    - asset/image/project/30-cannon-street/cannon-street-2.jpg
    - asset/image/project/30-cannon-street/cannon-street-3.jpg
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/american-school"
  imagePath: asset/image/project/american-school/main-american-school2.jpg
  imageList:
    - asset/image/project/american-school/american-school-1.jpg
    - asset/image/project/american-school/american-school-2.jpg
    - asset/image/project/american-school/american-school-3.jpg
    - asset/image/project/american-school/american-school-4.jpg
    - asset/image/project/american-school/american-school-5.jpg
  title: American School
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa
  
- link: "project/chelsea-barracks"
  imagePath: asset/image/project/chelsea-barracks/main-chelsea-barracks-2.jpg
  imageList:
    - asset/image/project/chelsea-barracks/chelsea-barracks-1.jpg
    - asset/image/project/chelsea-barracks/chelsea-barracks-3.jpg
  title: Chelsea Barracks
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/kensington-row"
  imagePath: asset/image/project/kensington-row/main-kensington-row.jpg
  imageList:
    - asset/image/project/kensington-row/kensington-row-1.jpg
    - asset/image/project/kensington-row/kensington-row-3.jpg
  title: Kensington Row
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/lancon-house"
  imagePath: asset/image/project/lancon-house/main-lancon-3.jpg
  imageList:
    - asset/image/project/lancon-house/lancon-1.jpg
    - asset/image/project/lancon-house/lancon-2.jpg
  title: Lancon House
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/lillie-square"
  imagePath: asset/image/project/lillie-square/main-lillie-square-3.jpg
  imageList:
    - asset/image/project/lillie-square/3lillie-square-1.jpg
    - asset/image/project/lillie-square/lillie-square-2.jpg
    - asset/image/project/lillie-square/lillie-square-3.jpg
  title: Lillie Square
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/one-tower-bridge-building-5"
  imagePath: asset/image/project/one-tower-bridge-building-5/main-one-tower-bridge-london.jpg
  imageList:
    - asset/image/project/one-tower-bridge-building-5/one-tower-1.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-2.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-3.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-4.jpg
  title: One Tower Bridge Building 5
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/one-finsbury-circus"
  imagePath: asset/image/project/one-finsbury-circus/main-roofs-6-finsbury.jpg
  imageList:
    - asset/image/project/one-finsbury-circus/finsbury-circus-1.jpg
    - asset/image/project/one-finsbury-circus/finsbury-circus-2.jpg
  title: One Finsbury Circus
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/river-walk"
  imagePath: asset/image/project/river-walk/river-walk-3.jpg
  imageList:
    - asset/image/project/river-walk/river-walk-1.jpg
  title: River Walk
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/triangle-cambridge"
  imagePath: asset/image/project/triangle-cambridge/main-triangle-4.jpg
  imageList:
    - asset/image/project/triangle-cambridge/image3.jpg
    - asset/image/project/triangle-cambridge/triangle-1.jpg
    - asset/image/project/triangle-cambridge/triangle-2.jpg
  title: Triangle Cambridge
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/tottenham-court-road"
  imagePath: asset/image/project/tottenham-court-road/tottenham-1.jpg
  imageList:
    - asset/image/project/tottenham-court-road/tottenham-2.jpg
    - asset/image/project/tottenham-court-road/tottenham-3.jpg
  title: Tottenham Court Road
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/1-harman-boulevard-manchester"
  imagePath: asset/image/project/1-harman-boulevard-manchester/main-harman-boulevard.jpg
  title: 1 Harman Boulevard Banchester
  imageList:
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-1.jpg
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-2.jpg
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-3.jpg
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!

- link: "project/cathedral-lane-shopping-centre-coventry"
  imagePath: asset/image/project/cathedral-lane-shopping-centre-coventry/main-coventry.jpg
  imageList:
    - asset/image/project/cathedral-lane-shopping-centre-coventry/coventry1.jpg
  title: Cathedral Lane Shopping Centre Coventry
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa

- link: "project/thomas-more"
  imagePath: asset/image/project/thomas-more/main-thomas-more3.jpg
  imageList:
    - asset/image/project/thomas-more/thomas-more.jpg
    - asset/image/project/thomas-more/thomas-more1.jpg
    - asset/image/project/thomas-more/thomas-more2.jpg
  title: Thomas More
  descriptionList:
    - Lorem is a good way to discover new paths
    - Hello sweet World!!!!
    - Add some more content extraa




